/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daniel Agurcia
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jD_ventanaAdmin = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jD_ventanaCliente = new javax.swing.JDialog();
        jD_ventanaMarketing = new javax.swing.JDialog();
        jD_servicioVehiculo = new javax.swing.JDialog();
        jL_usernameIcon = new javax.swing.JLabel();
        jTF_username = new javax.swing.JTextField();
        jL_passwordIcon = new javax.swing.JLabel();
        jP_password = new javax.swing.JPasswordField();
        jB_login = new javax.swing.JButton();
        jP_memberLogin = new javax.swing.JPanel();
        jL_MemberLogin = new javax.swing.JLabel();
        jL_ImagenPrincipal = new javax.swing.JLabel();

        jD_ventanaAdmin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\anadir (2).png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 150));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\fabrica.png")); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 70, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\comerciante.png")); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\proveedor.png")); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 70, 80));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\bolso.png")); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 70, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\empresa.png")); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 70, 70));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\cliente.png")); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 70, 70));

        jButton1.setText("Ejecutar");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, 114, 51));

        jRadioButton1.setBackground(new java.awt.Color(51, 255, 102));
        buttonGroup1.add(jRadioButton1);
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        buttonGroup2.add(jRadioButton4);
        jPanel3.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        buttonGroup2.add(jRadioButton5);
        jPanel3.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        buttonGroup2.add(jRadioButton6);
        jPanel3.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        buttonGroup2.add(jRadioButton7);
        jPanel3.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, -1, -1));

        buttonGroup2.add(jRadioButton9);
        jPanel3.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, -1, -1));

        buttonGroup2.add(jRadioButton10);
        jPanel3.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, -1, -1));

        buttonGroup2.add(jRadioButton11);
        jRadioButton11.setToolTipText("");
        jPanel3.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\coche.png")); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 70, 70));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Planta de Fabricacion");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Vehiculo");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Vendedor");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Proveedor");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Marca");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, -1, -1));

        jLabel18.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Compania");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, -1, -1));

        jLabel19.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Cliente");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, -1, -1));

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Crear");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel23.setBackground(new java.awt.Color(51, 51, 51));
        jLabel23.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Seleccione la entidad que desea aplicarle lo antes seleccionado:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel24.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Seleccione lo que desea realizar:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\borrar (2).png")); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 127, 142));

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Eliminar");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jPanel3.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 20, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\pluma (2).png")); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 127, 142));

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Modificar");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(51, 255, 102));
        buttonGroup1.add(jRadioButton2);
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\concesionario.png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 70, 70));

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Consecionario");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, 20));

        buttonGroup2.add(jRadioButton8);
        jPanel1.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 740));

        jTabbedPane2.addTab("CRUD", jPanel3);

        jD_ventanaAdmin.getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 770));

        javax.swing.GroupLayout jD_ventanaClienteLayout = new javax.swing.GroupLayout(jD_ventanaCliente.getContentPane());
        jD_ventanaCliente.getContentPane().setLayout(jD_ventanaClienteLayout);
        jD_ventanaClienteLayout.setHorizontalGroup(
            jD_ventanaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jD_ventanaClienteLayout.setVerticalGroup(
            jD_ventanaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jD_ventanaMarketingLayout = new javax.swing.GroupLayout(jD_ventanaMarketing.getContentPane());
        jD_ventanaMarketing.getContentPane().setLayout(jD_ventanaMarketingLayout);
        jD_ventanaMarketingLayout.setHorizontalGroup(
            jD_ventanaMarketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jD_ventanaMarketingLayout.setVerticalGroup(
            jD_ventanaMarketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jD_servicioVehiculoLayout = new javax.swing.GroupLayout(jD_servicioVehiculo.getContentPane());
        jD_servicioVehiculo.getContentPane().setLayout(jD_servicioVehiculoLayout);
        jD_servicioVehiculoLayout.setHorizontalGroup(
            jD_servicioVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jD_servicioVehiculoLayout.setVerticalGroup(
            jD_servicioVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_usernameIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\hombre (4).png")); // NOI18N
        getContentPane().add(jL_usernameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 30, 40));

        jTF_username.setBackground(new java.awt.Color(204, 204, 204));
        jTF_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_username.setToolTipText("  ");
        jTF_username.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, null));
        getContentPane().add(jTF_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 210, 40));

        jL_passwordIcon.setBackground(new java.awt.Color(204, 255, 51));
        jL_passwordIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\palabra-clave (2).png")); // NOI18N
        getContentPane().add(jL_passwordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 40, 40));

        jP_password.setBackground(new java.awt.Color(204, 204, 204));
        jP_password.setForeground(new java.awt.Color(0, 0, 0));
        jP_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jP_password.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, null));
        getContentPane().add(jP_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 210, 40));

        jB_login.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 24)); // NOI18N
        jB_login.setForeground(new java.awt.Color(0, 0, 0));
        jB_login.setText("Login");
        jB_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jB_login.setContentAreaFilled(false);
        getContentPane().add(jB_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 140, 50));

        jP_memberLogin.setBackground(new java.awt.Color(230, 255, 240));
        jP_memberLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 6, true));

        jL_MemberLogin.setBackground(new java.awt.Color(204, 255, 255));
        jL_MemberLogin.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 65)); // NOI18N
        jL_MemberLogin.setForeground(new java.awt.Color(102, 102, 102));
        jL_MemberLogin.setText("Member Login");
        jL_MemberLogin.setBorder(null);

        javax.swing.GroupLayout jP_memberLoginLayout = new javax.swing.GroupLayout(jP_memberLogin);
        jP_memberLogin.setLayout(jP_memberLoginLayout);
        jP_memberLoginLayout.setHorizontalGroup(
            jP_memberLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_memberLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_MemberLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_memberLoginLayout.setVerticalGroup(
            jP_memberLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_MemberLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        getContentPane().add(jP_memberLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 280, 90));

        jL_ImagenPrincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Agurcia\\Desktop\\Teoria BD1\\Proyecto Final\\Imagenes\\663e2c69c7d2723ac219c3f00dad3dae.jpg")); // NOI18N
        getContentPane().add(jL_ImagenPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jB_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jD_servicioVehiculo;
    private javax.swing.JDialog jD_ventanaAdmin;
    private javax.swing.JDialog jD_ventanaCliente;
    private javax.swing.JDialog jD_ventanaMarketing;
    private javax.swing.JLabel jL_ImagenPrincipal;
    private javax.swing.JLabel jL_MemberLogin;
    private javax.swing.JLabel jL_passwordIcon;
    private javax.swing.JLabel jL_usernameIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jP_memberLogin;
    private javax.swing.JPasswordField jP_password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTF_username;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
